name: Admin Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove existing directory
        run: rm -rf /var/www/vhosts/mobledec.com/admin.mobledec.com

      - name: Clone repository
        run: git clone https://github.com/emavi98/mobledec-admin /var/www/vhosts/mobledec.com/admin.mobledec.com/

      - name: Move to repository directory
        run: cd /var/www/vhosts/mobledec.com/admin.mobledec.com/

      - name: Build and push Frontend admin Docker image
        run: docker build -t mobledec_admin /var/www/vhosts/mobledec.com/admin.mobledec.com/

      - name: Stop and remove previous container
        run: docker stop $(docker ps -q --filter ancestor=mobledec_admin) && docker rm $(docker ps -aq --filter ancestor=mobledec_admin)

      - name: Run Docker container
        run: docker run -d -p 28741:80 --memory=3000m --restart=always --name mobledec_admin mobledec_admin
