name: Admin Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean build directory
        run: rm -rf /var/www/vs/admin.mobledec.com/*

      - name: Clone repository
        run: git clone https://github.com/emavi98/mobledec-admin /var/www/vs/admin.mobledec.com/

      - name: Move to parent directory
        run: cd ..

      - name: Build and push Frontend admin Docker image
        run: docker build -t mobledec_admin /var/www/vs/admin.mobledec.com

      - name: Run Docker container
        run: docker run -d -p 28560:80 --memory=3000m --restart=always mobledec_admin
