name: Admin Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_MOBLEDEC_ADMIN }}

      - name: Remove existing directory
        run: rm -rf /var/www/vhosts/mobledec.com/admin.mobledec.com

      - name: Clone repository
        run: git clone https://github.com/emavi98/mobledec-admin /var/www/vhosts/mobledec.com/admin.mobledec.com/
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_MOBLEDEC_ADMIN }}

      - name: Move to repository directory
        run: cd /var/www/vhosts/mobledec.com/admin.mobledec.com/

      - name: Build and push Frontend admin Docker image
        run: docker build -t mobledec_admin /var/www/vhosts/mobledec.com/admin.mobledec.com/

      # Limpiar imágenes sin etiquetas
      - name: Clean Docker images
        run: docker rmi $(docker images -q -f dangling=true) || true

      # Detener y eliminar el contenedor existente
      - name: Stop and remove previous container
        run: docker stop mobledec_admin || true && docker rm mobledec_admin || true

      - name: Run Docker container
        run: docker run -d -p 28741:80 --memory=3000m --restart=always --name mobledec_admin mobledec_admin
